name: Publish PgOSM-Flex Docker image
on:
  push:
    branches:
      - main
      - v0_2_0_rc
jobs:
  push_to_registry:
    name: Push PgOSM-Flex image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and Push to Docker Hub
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rustprooflabs/pgosm-flex:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

